name: 'banking_fraud_analytics'
version: '1.0.0'

flags:
  use_managed_iceberg: true
  use_materialization_v2: true
  use_concurrent_microbatch: true

profile: 'banking_fraud_analytics'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  banking_fraud_analytics:
    +persist_docs:
      relation: true
      columns: true
    bronze:
      +materialized: table
      +schema: bronze
    silver:
      +materialized: table
      +schema: silver
    gold:
      +materialized: table
      +schema: gold

seeds:
  banking_fraud_analytics:
    +schema: seeds